SERVICE_OPTIONS = [
    "Apteka",
    "Przychodnia lekarska",
    "Szkoła podstawowa",
    "Przedszkole",
    "Plac zabaw",
    "Biblioteka",
    "Piekarnia",
    "Kawiarnia",
    "Restauracja",
    "Siłownia",
    "Park",
    "Sklep odzieżowy",
    "Salon kosmetyczny",
    "Warsztat samochodowy",
    "Stacja benzynowa",
    "Poczta",
    "Bank/Bankomat",
    "Pralnia chemiczna",
    "Sklep RTV/AGD",
    "Centrum kultury",
    "Sklep zoologiczny",
    "Weterynarz",
    "Sklep budowlany",
    "Targowisko",
    "Dom seniora",
    "Serwis rowerowy",
    "Wypożyczalnia książek i filmów",
    "Usługi krawieckie",
    "Punkt naprawy telefonów/elektroniki",
    "Inne",
]