SERVICE_OPTIONS = [
    "Pharmacy",
    "Medical Clinic",
    "Primary School",
    "Kindergarten",
    "Playground",
    "Library",
    "Bakery",
    "Cafe",
    "Restaurant",
    "Gym",
    "Park",
    "Clothing Store",
    "Beauty Salon",
    "Car Workshop",
    "Gas Station",
    "Post Office",
    "Bank/ATM",
    "Dry Cleaning",
    "Electronics Store",
    "Cultural Center",
    "Pet Store",
    "Veterinary Clinic",
    "Hardware Store",
    "Marketplace",
    "Senior Home",
    "Bicycle Service",
    "Book and Movie Rental",
    "Tailoring Services",
    "Phone/Electronics Repair",
    "Other",
]

PREMISE_DEMAND_PRIORITY = [
    "Low",
    "Medium",
    "High",
]

PREMISE_OPTIONS = []